### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [is541-sibsutis/password-generator#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:

1. В [wiki](https://github.com/is541-sibsutis/password-generator/wiki) проекта написана статья с ТЗ.
1. В [issues](https://github.com/is541-sibsutis/password-generator/issues) созданы задачи.
1. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by Doshinsky** [comment]
- [ ] [Статья](https://github.com/is541-sibsutis/password-generator/wiki/Добро-пожаловать-на-wiki-страницу-генератора-паролей!) написана!

- [ ] В разделе Issues созданы все необходимые [задачи](https://github.com/is541-sibsutis/password-generator/issues)!

@evgeny-p

**Comment by evgeny-p** [comment]
Вопросы по ТЗ.

1. Уточните, пожалуйста, как предполагается реализовать генерацию паролей без повторов:
  1. Алгоритм проверки уникальности пароля.
  1. Способ и формат хранения данных, необходимых для проверки уникальности пароля.

1. Если приложение будет реализовано как веб-сервис, то нужно описать протокол взаимодействия с ним (API). Например, можно гуглить по слову REST.

1. Как будет реализована обработка запросов клиента? Приложение само будет сервером или в качестве фронтенда планируется использовать nginx/apache/etc?

Замечания по задачам.

1. Предлагаю убрать из заголовков задач часть «Задание #X». Задачи и так имеют номера, по которым на них можно ссылаться. Ниже по тексту используется нумерация гитхаба.

1. Задача #2 дублирует текущую.

1. Задача #3 состоит из трех подзадач. Имеет смысл декомпозировать. Таким образом, все три подзадачи могут делать параллельно разные люди.

1. В задача #4 описаны процессы, являющиеся необходимым definition of done каждой задачи. Предполагается, что в процессе работы над любой задачей помимо функционала должны быть реализованы тесты. Отладка также выполняется в процессе по необходимости. Если в приложении будут найдены ошибки, то на них заводятся отдельные задачи с конкретными формулировками. На основании этого предлагаю задачу убрать.

1. Уточните, пожалуйста, что входит в задачу #5. Разработка серверной части? Настройка инфраструктуры? Разработка интерфейса? Возможно, эту задачу также нужно декомпозировать на более мелкие.

1. В задаче #5 предлагаю оставить только последний пункт. Его можно переформулировать как «Подготовка демонстрации приложения». В результате выполнения работы должна быть подготовлена презентация и продуман сценарий демонстрации приложения на защите. По остальным пунктам в этой задаче:
  1. Сборка приложения — должна быть настроена в одной из первых задач.
  1. Стандарты кодирования должны соблюдаться всегда. Любая из предшествующих задач считается невыполненной, если код не соответствует выбранным соглашениям.
  1. Приемочное тестирование можно оформить как отдельную задачу.

PS
Неплохо бы отметить, каких соглашений о кодировании будете придерживаться в проекте.

**Comment by Doshinsky** [comment]
Вроде бы все пункты проверил и исправил.
Сразу еще раз хотел бы уточнить:
 
> Уточните, пожалуйста, как предполагается реализовать генерацию паролей без повторов:
> Алгоритм проверки уникальности пароля.
> Способ и формат хранения данных, необходимых для проверки уникальности пароля.  
  
Данный вопрос мы активно обсуждаем, но пока еще не решили, как это сделать. Именно, поэтому я не стал уточнять эту деталь в ТЗ и задачах  
___  
> Если приложение будет реализовано как веб-сервис, то нужно описать протокол взаимодействия с ним (API). Например, можно гуглить по слову REST.  
> Как будет реализована обработка запросов клиента? Приложение само будет сервером или в качестве фронтенда планируется использовать nginx/apache/etc?

Человек ответственный за реализацию web-интерфейса, пока не дал тоже ответа.


_P.S. Мы добавим всё необходимое по мере возможностей и решения этих вопросов_

@evgeny-p

**Comment by evgeny-p** [comment]
> Мы добавим всё необходимое по мере возможностей и решения этих вопросов

Если есть вопросы, требующие обсуждения, продумывания и, как следствие, затрат времени, на них тоже можно завести задачи. Например, результатом задачи «Предложить способ генерации уникальных паролей» может быть статья в вики с тех. предложением. А на кодирование — отдельная задача, которая у вас уже заведена. Аналогично можно завести задачу на разработку API.

В задаче #5 под интерфейсом понимается программный (API) или пользовательский интерфейс? Если второе, то эту часть можно оформить как отдельную задачу и разрабатывать параллельно с сервером.

ТЗ и план работ принимаются.

В процессе работы над проектом могут создаваться новые задачи и уточняться существующие.
