### ISSUE TITLE
Проблема с Travis CI

### ISSUE THREAD

**Issue by Doshinsky** [is541-sibsutis/password-generator#10]
Создал файл `.travis.yml` для постоянной интеграции на Travis'е, но он не видит данный файл:
![image](https://cloud.githubusercontent.com/assets/17213440/14774898/cb115806-0adc-11e6-8796-41400c3c56ca.png)
В мануалах нашёл следующую пометку:

> Note: You can only enable Travis CI builds for repositories you have admin access to.

Внимание, вопрос:
А есть ли у меня данные права? 
Если нет, то как мне их получить?
Если да, то почему ничего не получается?

@evgeny-p

**Comment by evgeny-p** [comment]
Настроил доступ, проверьте сейчас.

**Comment by Doshinsky** [comment]
Нет, проблема не устранена, но я, кажется, понял в чем суть:
У нас нет мёржа с мастер-веткой, а Travis ссылается на неё, в то время как `.travis.yml` находится в ветке `Development-branch`.
Что в таком случае лучше всего сделать?

@evgeny-p

**Comment by Doshinsky** [comment]
Все, проблема устранена.

@evgeny-p
