### ISSUE TITLE
Документация ГОСТ

### ISSUE THREAD

**Issue by Doshinsky** [is541-sibsutis/password-generator#11]
У нас возникли вопросы по составлению документации к проекту. Не знаем, как ответить на них, нужна помощь. Еще было неплохо, если сказали, что вообще должно быть в документации к нашем проекту, или ссылку на необходимые критерии, на всякий случай.

Вопросы:
1)Объём оперативной памяти необходимый для выполнения программы

2) Требование к программному обеспечению

3)Требование к персоналу (программисту)(знания программирования)

4)Контроль правильности выполнения программы

5)Организация используемой входной информации

6) Есть ли возможность появления сообщений об ошибке и какие они бывают

@evgeny-p

**Comment by evgeny-p** [comment]
Вы говорите о пользовательской документации или об отчете по курсовому?

**Comment by Denissimos** [comment]
Речь идёт о документации
