### ISSUE TITLE
Проблема с составом

### ISSUE THREAD

**Issue by Doshinsky** [is541-sibsutis/password-generator#8]
У нас есть _маленькая_ проблема с личным составом. В нашей группе четыре человека, из которых работают **трое**, в то время как последний ничего не сделал полезного для развития проекта уже на протяжении месяца.
Что делать с этим человеком так, чтобы из-за него остальные **не пострадали** на защите? Мотивировать его **никак** не получается ни у одного из нас, ни просьбами, ни угрозами, ни иным другим способом.

@evgeny-p

**Comment by evgeny-p** [comment]
На паре договорились, что дальнейшую работу планируем на трех человек. Создали milestone Beta, включите в него задачи, которые планируется выполнить к бета-версии.

Оценивать работу будем по факту выполнения. Какие выбрать критерии для оценки человека, не участвующего в работе — у меня пока нет идей.

**Comment by Doshinsky** [comment]
В принципе, я попытаюсь свалить на него хотя бы документацию, может хоть тут он поработает и всё обойдётся. Ну, а если нет, то удачи ему пожелаю на экзамене.

В течение недели дополню `milestone Beta` и отпишусь в этом же issue

**Comment by Doshinsky** [comment]
Мы доработали код, отвечающий за уникальность паролей, но он немного сырой, ему нужна оптимизация и покрытие тестами.

В `milestone Beta` добавил задачу, отвечающую за это. Сам код запушу ближе к пятнице.

@evgeny-p

**Comment by evgeny-p** [comment]
Предложенные меры вполне законны.

В рамках этой задачи еще остались нерешенные вопросы?

**Comment by Doshinsky** [comment]
В рамках данной задачи вопросов пока нет, но в течение дня заведу еще две: по поводу Web-интерфейса и Unit-тестов.

@evgeny-p
